### ISSUE TITLE
SC-200 violation

### ISSUE THREAD

**Issue by jgmuchiri** [BloomTech-Labs/story-squad-be-archived#108]
RE: [#sc-200-never-store-secrets](https://lambda-school-labs.github.io/labs-engineering-standards/topics/security/#sc-200-never-store-secrets)

Stripe secret key: This lives in the secrets world

https://github.com/Lambda-School-Labs/story-squad-be/wiki/Setup-Guide

**Comment by Evrgreen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Address SC-200 Violation](https://trello.com/c/47FHf3yW/30-address-sc-200-violation)

**Comment by lgv-0** [comment]
Removed from wiki and code in b6eb53d80610df71edd3d2841ee7a3b1212bbf51 & [wiki:de692af](https://github.com/Lambda-School-Labs/story-squad-be/wiki/Setup-Guide/de692af70fb846d9f12a9071325312d9db4bebe2)
